/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const partnerCreated = require('./code/PartnerCreated');

class BusinessPartner_0101 extends LCAPApplicationService {
    async init() {
        const em_sap_s4_beh_businesspartner_v1_BusinessPartner = await cds.connect.to('sap.s4.beh.businesspartner.v1.BusinessPartner');
        em_sap_s4_beh_businesspartner_v1_BusinessPartner.on('Created.v1', async message => {
            await partnerCreated(message);
        });

        return super.init();
    }
}


module.exports = {
    BusinessPartner_0101
};